"""Bivariate bicycle (BB) codes of Bravyi et al., arXiv:2308.07915.

H_X = [A | B], H_Z = [B^T | A^T] with A, B sums of monomials in x = S_l (x) I_m and
y = I_l (x) S_m. Check ``c = i*m + j`` corresponds to the monomial x^i y^j.
"""

import numpy as np
import scipy.sparse

import ldpc.mod2


def _shift(size, power):
    return np.roll(np.eye(size, dtype=np.uint8), power, axis=1)


def _poly(l, m, terms):
    """Sum of monomials; each term is ('x', a) or ('y', b)."""
    out = np.zeros((l * m, l * m), dtype=np.uint8)
    for var, a in terms:
        mono = np.kron(_shift(l, a), np.eye(m, dtype=np.uint8)) if var == "x" else \
            np.kron(np.eye(l, dtype=np.uint8), _shift(m, a))
        out ^= mono
    return out


# name: (l, m, A terms, B terms, published distance)
BB_CODES = {
    "[[72,12,6]]": (6, 6, [("x", 3), ("y", 1), ("y", 2)], [("y", 3), ("x", 1), ("x", 2)], 6),
    "[[90,8,10]]": (15, 3, [("x", 9), ("y", 1), ("y", 2)], [("x", 0), ("x", 2), ("x", 7)], 10),
    "[[108,8,10]]": (9, 6, [("x", 3), ("y", 1), ("y", 2)], [("y", 3), ("x", 1), ("x", 2)], 10),
    "[[144,12,12]]": (12, 6, [("x", 3), ("y", 1), ("y", 2)], [("y", 3), ("x", 1), ("x", 2)], 12),
    "[[288,12,18]]": (12, 12, [("x", 3), ("y", 2), ("y", 7)], [("y", 3), ("x", 1), ("x", 2)], 18),
    # distances of the two largest codes are upper bounds in the paper
    "[[360,12,<=24]]": (30, 6, [("x", 9), ("y", 1), ("y", 2)], [("y", 3), ("x", 25), ("x", 26)], 24),
    "[[756,16,<=34]]": (21, 18, [("x", 3), ("y", 10), ("y", 17)], [("y", 5), ("x", 3), ("x", 19)], 34),
}


def css_logicals(h_commute, h_stab):
    """Basis of ker(h_commute) modulo rowspace(h_stab)."""
    ker = scipy.sparse.csr_matrix(ldpc.mod2.kernel(h_commute))
    stacked = scipy.sparse.vstack([scipy.sparse.csr_matrix(h_stab), ker]).tocsr()
    piv = np.asarray(ldpc.mod2.pivot_rows(stacked))
    rows = [p - h_stab.shape[0] for p in piv if p >= h_stab.shape[0]]
    return ker[rows].toarray().astype(np.uint8) % 2


class BBCode:
    def __init__(self, name):
        l, m, a, b, d = BB_CODES[name]
        A, B = _poly(l, m, a), _poly(l, m, b)
        self.name, self.l, self.m, self.d = name, l, m, d
        self.hx = scipy.sparse.csr_matrix(np.hstack([A, B]))
        self.hz = scipy.sparse.csr_matrix(np.hstack([B.T, A.T]))
        assert not ((self.hx @ self.hz.T).toarray() % 2).any()
        self.n = self.hx.shape[1]
        self.lz = css_logicals(self.hx, self.hz)   # detects X-type residuals
        self.lx = css_logicals(self.hz, self.hx)
        self.k = self.lz.shape[0]


def coset_groups(code, step_x, size_x, step_y, size_y):
    """Groups of checks x^i y^j forming cosets of the subgroup generated by x^step_x (size_x
    elements) and y^step_y (size_y elements). Row index of x^i y^j is i*m + j."""
    l, m = code.l, code.m
    seen, groups = set(), []
    for i0 in range(l):
        for j0 in range(m):
            if (i0, j0) in seen:
                continue
            g = [((i0 + a * step_x) % l, (j0 + b * step_y) % m) for a in range(size_x) for b in range(size_y)]
            seen.update(g)
            groups.append(sorted(i * m + j for i, j in g))
    return groups
