"""Compare coset-based check groupings for LRB-MS on [[144,12,12]] (l = 12, m = 6).

Usage: python explore3.py
"""

import multiprocessing as mp

from harness import simulate

CODE = "[[144,12,12]]"
SHOTS = 4000

# (label, decoder spec); ("coset", step_x, size_x, step_y, size_y) groups the checks x^i y^j
# into cosets of the subgroup generated by x^step_x (size_x elements) and y^step_y (size_y)
SPECS = [
    ("greedy ell=6", dict(kind="lrbms", groups=6)),
    ("y-cosets (6)", dict(kind="lrbms", groups=("coset", 1, 1, 1, 6))),
    ("y^3-cosets (2)", dict(kind="lrbms", groups=("coset", 1, 1, 3, 2))),
    ("y^2-cosets (3)", dict(kind="lrbms", groups=("coset", 1, 1, 2, 3))),
    ("x^6-cosets (2)", dict(kind="lrbms", groups=("coset", 6, 2, 1, 1))),
    ("x^4-cosets (3)", dict(kind="lrbms", groups=("coset", 4, 3, 1, 1))),
    ("x^3-cosets (4)", dict(kind="lrbms", groups=("coset", 3, 4, 1, 1))),
    ("x^3,y^3 (8)", dict(kind="lrbms", groups=("coset", 3, 4, 3, 2))),
    ("x-cosets (12)", dict(kind="lrbms", groups=("coset", 1, 12, 1, 1))),
    ("x^6,y^2 (6)", dict(kind="lrbms", groups=("coset", 6, 2, 2, 3))),
    ("x^4,y^3 (6)", dict(kind="lrbms", groups=("coset", 4, 3, 3, 2))),
]


def main():
    with mp.Pool(4) as pool:
        for p in [0.05]:
            for label, spec in SPECS:
                result = simulate(pool, CODE, spec, p, SHOTS, 10**9, 250, 11 + int(p * 1000))
                print(
                    f"p={p} {label:>16}: LER={result['fails'] / result['shots']:.3e} "
                    f"({result['fails']}/{result['shots']}) "
                    f"unconv={result['unconverged']} {result['us_per_shot']:.0f}us",
                    flush=True,
                )


if __name__ == "__main__":
    main()
